"""create download job and item tables

Revision ID: 5f1cf7039102
Revises: 
Create Date: 2026-09-23 17:34:09.298090

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '5f1cf7039102'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('download_jobs',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('source_url', sa.Text(), nullable=False),
    sa.Column('playlist_id', sa.String(length=128), nullable=True),
    sa.Column('playlist_title', sa.String(length=512), nullable=True),
    sa.Column('output_directory', sa.Text(), nullable=False),
    sa.Column('format_preset', sa.String(length=32), nullable=False),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.Column('total_items', sa.Integer(), nullable=False),
    sa.Column('completed_items', sa.Integer(), nullable=False),
    sa.Column('failed_items', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('finished_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_download_jobs_status'), 'download_jobs', ['status'], unique=False)
    op.create_table('download_items',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('job_id', sa.String(length=36), nullable=False),
    sa.Column('video_id', sa.String(length=32), nullable=True),
    sa.Column('title', sa.String(length=512), nullable=False),
    sa.Column('playlist_index', sa.Integer(), nullable=True),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.Column('progress', sa.Float(), nullable=False),
    sa.Column('downloaded_bytes', sa.Integer(), nullable=False),
    sa.Column('total_bytes', sa.Integer(), nullable=True),
    sa.Column('speed', sa.Float(), nullable=True),
    sa.Column('eta', sa.Float(), nullable=True),
    sa.Column('output_path', sa.Text(), nullable=True),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['job_id'], ['download_jobs.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_download_items_job_id'), 'download_items', ['job_id'], unique=False)
    op.create_index(op.f('ix_download_items_status'), 'download_items', ['status'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_download_items_status'), table_name='download_items')
    op.drop_index(op.f('ix_download_items_job_id'), table_name='download_items')
    op.drop_table('download_items')
    op.drop_index(op.f('ix_download_jobs_status'), table_name='download_jobs')
    op.drop_table('download_jobs')
    # ### end Alembic commands ###
